import fs from 'fs';
const code = [
"'use client';",
"import { useEffect } from 'react';",
"import { useRouter } from 'next/navigation';",
"import PublicLayout from '@/components/layout/PublicLayout';",
"import { useAuth } from '@/context/AuthContext';",
"import Button from '@/components/ui/Button';",
"import Card from '@/components/ui/Card';",
"import Badge from '@/components/ui/Badge';",
"import styles from './page.module.css';",
"",
"export default function PerfilPage() {",
"  const { user, isAuthenticated, authLoading, logout } = useAuth();",
"  const router = useRouter();",
"",
"  useEffect(() => {",
"    if (authLoading) return;",
"    if (!isAuthenticated) router.push('/login');",
"  }, [authLoading, isAuthenticated]);",
"",
"  if (!user) return null;",
"",
"  const handleLogout = () => { logout(); router.push('/'); };",
"",
"  return (",
"    <PublicLayout>",
"      <div className='container'>",
"        <h1 className={styles.title}>Mi perfil</h1>",
"        <div className={styles.layout}>",
"          <Card>",
"            <div className={styles.avatar}>{user.nombre[0]}{user.apellido[0]}</div>",
"            <h2 className={styles.nombre}>{user.nombre} {user.apellido}</h2>",
"            <p className={styles.email}>{user.email}</p>",
"            <Badge variant={user.rol === 'ADMINISTRADOR' ? 'warning' : 'info'}>{user.rol}</Badge>",
"          </Card>",
"          <div className={styles.actions}>",
"            <Card>",
"              <h3 className={styles.sectionTitle}>Acciones rapidas</h3>",
"              <div className={styles.actionList}>",
"                <Button variant='secondary' fullWidth onClick={() => router.push('/catalogo')}>Ver catalogo</Button>",
"                <Button variant='secondary' fullWidth onClick={() => router.push('/carrito')}>Mi carrito</Button>",
"                <Button variant='danger' fullWidth onClick={handleLogout}>Cerrar sesion</Button>",
"              </div>",
"            </Card>",
"          </div>",
"        </div>",
"      </div>",
"    </PublicLayout>",
"  );",
"}",
].join('\n');
fs.writeFileSync('src/app/perfil/page.tsx', code);
console.log('ok');
