import fs from 'fs';
let l = fs.readFileSync('src/app/admin/reportes/page.tsx', 'utf8').split('\n');
l[26] = "          api.get<any>('/admin/reportes/categorias'),";
l[27] = "          api.get<any>('/admin/reportes/stock'),";
l[29] = "          const catMap = catRes.data.categorias || {};";
l[30] = "          const catArr = Object.entries(catMap).map(([cat, count]) => ({ categoria: cat, totalProductos: count as number, totalUnidades: count as number }));";
l[31] = "          setCategorias(catArr);";
l[32] = "          const st = stockRes.data;";
l[33] = "          setCriticos(st.bajo > 0 || st.sinStock > 0 ? [";
l[34] = "            ...(st.sinStock > 0 ? [{ id: 1, nombre: 'Productos sin stock', categoria: '', stock: 0, estado: 'AGOTADO' as const }] : []),";
l[35] = "            ...(st.bajo > 0 ? [{ id: 2, nombre: 'Productos con stock bajo', categoria: '', stock: st.bajo, estado: 'BAJO' as const }] : []),";
l[36] = "          ] : []);";
l[37] = "  const totalProductos = categorias.reduce((a, c) => a + c.totalProductos, 0);";
l[38] = "  const totalUnidades = categorias.reduce((a, c) => a + c.totalUnidades, 0);";
fs.writeFileSync('src/app/admin/reportes/page.tsx', l.join('\n'));
console.log('ok');
