import fs from 'fs';

const adminLayout = [
"'use client';",
"import { useState, useEffect } from 'react';",
"import Link from 'next/link';",
"import { usePathname, useRouter } from 'next/navigation';",
"import { useAuth } from '@/context/AuthContext';",
"import Logo from '@/components/ui/Logo';",
"import styles from './AdminLayout.module.css';",
"",
"const NAV = [",
"  { href: '/admin/productos', label: 'Productos' },",
"  { href: '/admin/stock', label: 'Stock' },",
"  { href: '/admin/reportes', label: 'Reportes' },",
"];",
"",
"export default function AdminLayout({ children }) {",
"  const pathname = usePathname();",
"  const router = useRouter();",
"  const { user, logout } = useAuth();",
"  const [mounted, setMounted] = useState(false);",
"  useEffect(() => { setMounted(true); }, []);",
"  const handleLogout = () => { logout(); router.push('/'); };",
"  if (!mounted) return null;",
"  return (",
"    <div className={styles.root}>",
"      <aside className={styles.sidebar}>",
"        <div className={styles.sidebarTop}>",
"          <Logo size={28} />",
"          <span className={styles.adminBadge}>Admin</span>",
"        </div>",
"        <nav className={styles.sidebarNav}>",
"          {NAV.map(n => (",
"            <Link key={n.href} href={n.href}",
"              className={styles.navItem + (pathname === n.href ? ' ' + styles.active : '')}>",
"              {n.label}",
"            </Link>",
"          ))}",
"        </nav>",
"        <div className={styles.sidebarBottom}>",
"          <span className={styles.userInfo}>{user?.nombre} {user?.apellido}</span>",
"          <button className={styles.logoutBtn} onClick={handleLogout}>Cerrar sesion</button>",
"        </div>",
"      </aside>",
"      <div className={styles.content}>",
"        <main className={styles.main}>{children}</main>",
"      </div>",
"    </div>",
"  );",
"}",
].join('\n');

const navbar = [
"'use client';",
"import { useState, useEffect } from 'react';",
"import Link from 'next/link';",
"import { useRouter } from 'next/navigation';",
"import { useAuth } from '@/context/AuthContext';",
"import Logo from '@/components/ui/Logo';",
"import Button from '@/components/ui/Button';",
"import styles from './Navbar.module.css';",
"",
"export default function Navbar() {",
"  const { user, logout, isAuthenticated, isAdmin, authLoading } = useAuth();",
"  const router = useRouter();",
"  const [mounted, setMounted] = useState(false);",
"  useEffect(() => { setMounted(true); }, []);",
"  const handleLogout = () => { logout(); router.push('/'); };",
"  if (!mounted || authLoading) return (",
"    <nav className={styles.nav}>",
"      <div className={'container ' + styles.inner}>",
"        <Link href='/'><Logo size={32} /></Link>",
"      </div>",
"    </nav>",
"  );",
"  return (",
"    <nav className={styles.nav}>",
"      <div className={'container ' + styles.inner}>",
"        <Link href={isAdmin ? '/admin/productos' : isAuthenticated ? '/catalogo' : '/'}>",
"          <Logo size={32} />",
"        </Link>",
"        <div className={styles.links}>",
"          {!isAuthenticated && <Link href='/catalogo' className={styles.link}>Catalogo</Link>}",
"          {isAuthenticated && !isAdmin && <>",
"            <Link href='/catalogo' className={styles.link}>Catalogo</Link>",
"            <Link href='/carrito' className={styles.link}>Carrito</Link>",
"            <Link href='/perfil' className={styles.link}>Perfil</Link>",
"          </>}",
"          {isAdmin && <>",
"            <Link href='/admin/productos' className={styles.link}>Productos</Link>",
"            <Link href='/admin/stock' className={styles.link}>Stock</Link>",
"            <Link href='/admin/reportes' className={styles.link}>Reportes</Link>",
"          </>}",
"        </div>",
"        <div className={styles.actions}>",
"          {!isAuthenticated ? <>",
"            <Link href='/login'><Button variant='ghost' size='sm'>Ingresar</Button></Link>",
"            <Link href='/register'><Button size='sm'>Registrarse</Button></Link>",
"          </> : <>",
"            <span className={styles.userName}>{user?.nombre}</span>",
"            <Button variant='ghost' size='sm' onClick={handleLogout}>Salir</Button>",
"          </>}",
"        </div>",
"      </div>",
"    </nav>",
"  );",
"}",
].join('\n');

fs.writeFileSync('src/components/layout/AdminLayout.tsx', adminLayout);
fs.writeFileSync('src/components/layout/Navbar.tsx', navbar);
console.log('ok');
