# Nombre de la aplicacion
spring.application.name=backend

# Conexion a PostgreSQL (lo que configuramos en Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/autostock
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate: crea/actualiza tablas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto donde corre el backend
server.port=8080

# JWT (para seguridad, token de autenticacion)
jwt.secret=miClaveSecretaMuyLargaParaAutoStockIA2026
jwt.expiration=86400000
